name: UI Automation

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  playwright-test:
    name: Run tests on ${{ matrix.os }} / Python ${{ matrix.python-version }}
    timeout-minutes: 15
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        python-version: [ '3.13' ]

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
    
    - name: Install dependencies
      run: |
        pip install --upgrade pip
        sudo apt-get update && sudo apt-get install allure
        pip install -r requirements.txt

    - name: Install Playwright browsers
      run: playwright install --with-deps

    - name: Run Playwright tests and collect Allure results
      run: pytest --alluredir allure-results
    
    - name: Generate Allure Report
      if: always()
      run: allure generate allure-results -o allure-report --clean
    
    - name: Upload Allure Report as Artifact
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: allure-report-static
        path: allure-report/
        retention-days: 30
    
    - name: Deploy Allure Report to GitHub Pages
      if: always()
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: allure-report
        keep_files: false
